deploy:
    image: python:3.10
    stage: deploy
    rules:
        - if: $CI_COMMIT_TAG                  # Run automatically on tags
        - if: $CI_PIPELINE_SOURCE == "web"    # Allow manual "Run Pipeline" from UI
    variables:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $TWINE_TOKEN
    script:
        - rm -rf dist
        - pip install twine build --verbose
        - python -m build --verbose
        - echo "Token length is ${#TWINE_TOKEN}"
        - python -m twine upload dist/* -u "__token__" -p "$TWINE_TOKEN" --verbose