deploy:
    image: python:3.10
    stage: deploy
    only:
        - tags
    variables:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
    script:
        - rm -rf dist
        - pip install twine build --verbose
        - python -m build --verbose
        - python -m twine upload dist/* --verbose